# Site settings
title: Cirkoan 公案
email: eliasrodrigo.com
description: >
        ...pela malabariavialbilidade em realidades paralelas.. 
url: "https://cirkoan.gitlab.io/"
gitlab_username:  cirkoan/cirkoan.gitlab.io
github_username:  lsrdg/cirkoan

# Build settings
markdown: kramdown
exclude: ["README.md"]
