# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cirkoan 公案
email: your-email@domain.com
description: >
        ...pela malabariavialbilidade em realidades paralelas.. 
url: "https://cirkoan.gitlab.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["README.md"]
